version: "3.8"

services:
    wakeonlan-web:
        image: fluidblue/wakeonlan-web:latest
        build:
            context: .
            dockerfile: Dockerfile
        init: true
        environment:
            DATABASE_HOST: "127.0.0.1"
            DATABASE_DB: "${DATABASE_DB}"
            DATABASE_USER: "${DATABASE_USER}"
            DATABASE_PASSWORD_FILE: "${DATABASE_PASSWORD_FILE_CONTAINER}"
        network_mode: "host"
        volumes:
            - ${DATABASE_PASSWORD_FILE_LOCAL}:${DATABASE_PASSWORD_FILE_CONTAINER}
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    mariadb:
        image: mariadb:10.6
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: "yes"
            MARIADB_DATABASE: "${DATABASE_DB}"
            MARIADB_USER: "${DATABASE_USER}"
            MARIADB_PASSWORD_FILE: "${DATABASE_PASSWORD_FILE_CONTAINER}"
        network_mode: "host"
        volumes:
            - mariadb-data:/var/lib/mysql
            - ${DATABASE_PASSWORD_FILE_LOCAL}:${DATABASE_PASSWORD_FILE_CONTAINER}
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    adminer:
        image: adminer
        restart: always
        network_mode: "host"

volumes:
    mariadb-data:
