version: "3.8"

# Hint: Versions and tags are set in the file ".env"

services:
    wakeonlan-web:
        image: fluidblue/wakeonlan-web:latest
        build:
            context: .
            dockerfile: Dockerfile
        init: true
        network_mode: "host"
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    mariadb:
        image: mariadb:10.6
        environment:
            MARIADB_ROOT_PASSWORD: "test_password"
        network_mode: "host"
        volumes:
            - mariadb-data:/var/lib/mysql
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    adminer:
        image: adminer
        restart: always
        network_mode: "host"

volumes:
    mariadb-data:
